# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f100ffeb27d95ba8440a0fbe4b0194903f2fed6738807f3f870bcd066b0b11e948231d3b1d5e159c9b3df0666fe05a13c7d9337e2f38d8b019c2cb97c5375da4

test:
  secret_key_base: 8e32e65ca674267d4a9aaa2e2299696fa559fb4bfb29d0cc0c04b3a434e238407e3c70eca65e5b628672ff5613499ebf1a847d46738770b698c3bed888cef1cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
